# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
    - unnecessary_lambdas
    - avoid_unnecessary_containers
    - prefer_if_null_operators
    - prefer_spread_collections
    - sort_child_properties_last
    - use_full_hex_values_for_flutter_colors

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
